//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPIDataEntities : DbContext
    {
        public CPIDataEntities()
            : base("name=CPIDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<CPIHardwareSoftware> CPIHardwareSoftwares { get; set; }
        public virtual DbSet<CPILookup> CPILookups { get; set; }
        public virtual DbSet<CPIMain> CPIMains { get; set; }
        public virtual DbSet<CPIModeling> CPIModelings { get; set; }
        public virtual DbSet<CPIModelingAttribute> CPIModelingAttributes { get; set; }
        public virtual DbSet<CPIModelingContainerSetContent> CPIModelingContainerSetContents { get; set; }
        public virtual DbSet<CPIModelingContainerSet> CPIModelingContainerSets { get; set; }
        public virtual DbSet<CPIOrganicAssessment> CPIOrganicAssessments { get; set; }
        public virtual DbSet<CPIProgram> CPIPrograms { get; set; }
        public virtual DbSet<CPIProject> CPIProjects { get; set; }
        public virtual DbSet<CPIProjectImportSetting> CPIProjectImportSettings { get; set; }
        public virtual DbSet<CPIRole> CPIRoles { get; set; }
        public virtual DbSet<CPIUser> CPIUsers { get; set; }
        public virtual DbSet<CPIUserPassword> CPIUserPasswords { get; set; }
        public virtual DbSet<CPIUserRole> CPIUserRoles { get; set; }
        public virtual DbSet<ObjectivesLookup> ObjectivesLookups { get; set; }
        public virtual DbSet<PlatformsLookup> PlatformsLookups { get; set; }
        public virtual DbSet<RelatedTechnologiesLookup> RelatedTechnologiesLookups { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<InfoLog> InfoLogs { get; set; }
        public virtual DbSet<ThreatsLookup> ThreatsLookups { get; set; }

        public System.Data.Entity.DbSet<MVCTesterCPI2.Models.CpiProject> CpiProjects { get; set; }
    }
}
