//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIHardwareSoftware
    {
        public int ID { get; set; }
        public int CPIID { get; set; }
        public bool IsCOTS { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string Manufacturer { get; set; }
        public string Criticality { get; set; }
    }
}
