//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIModeling
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string GUID { get; set; }
        public int CPIProjectID { get; set; }
        public string EntityName { get; set; }
        public string EntityType { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> Criticality { get; set; }
        public string HierarchyText { get; set; }
        public string LastEditBy { get; set; }
        public string LastEditDate { get; set; }
        public string CreatedDate { get; set; }
    }
}
