//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIModelingContainerSetContent
    {
        public int ID { get; set; }
        public int ModelingContainerSetID { get; set; }
        public Nullable<int> CPIModelingID { get; set; }
        public string CreatedDate { get; set; }
    }
}
