//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIOrganicAssessment
    {
        public int ID { get; set; }
        public int CPIID { get; set; }
        public bool InfoA { get; set; }
        public bool InfoB { get; set; }
        public bool InfoC { get; set; }
        public bool InfoD { get; set; }
        public bool ImpactA { get; set; }
        public bool ImpactB { get; set; }
        public bool ImpactC { get; set; }
        public bool ImpactD { get; set; }
        public bool ImpactE { get; set; }
        public bool ImpactF { get; set; }
        public bool SensitivityA { get; set; }
        public bool SensitivityB { get; set; }
        public bool SensitivityC { get; set; }
        public bool SensitivityD { get; set; }
        public bool FormatA { get; set; }
        public bool FormatB { get; set; }
        public bool FormatC { get; set; }
        public bool FormatD { get; set; }
        public string LastEditBy { get; set; }
        public string LastEditDate { get; set; }
        public string CreatedDate { get; set; }
    }
}
