//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIProjectImportSetting
    {
        public int ID { get; set; }
        public string FileType { get; set; }
        public int HierarchyColumnIndex { get; set; }
        public int EntityNameColumnIndex { get; set; }
        public int EntityTypeColumnIndex { get; set; }
        public int CriticalityColumnIndex { get; set; }
        public string LastEditBy { get; set; }
        public string LastEditDate { get; set; }
        public string CreatedDate { get; set; }
    }
}
