//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPIUser
    {
        public int ID { get; set; }
        public string CPIUsername { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LastLoginDate { get; set; }
        public string LastEditBy { get; set; }
        public string LastEditDate { get; set; }
        public string CreatedDate { get; set; }
    }
}
