//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTesterCPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int ID { get; set; }
        public string SurveyQuestionID { get; set; }
        public int CPIID { get; set; }
        public string Answer { get; set; }
        public string CreatedDate { get; set; }
    }
}
